In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
arr = np.array([1,2,3])
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myArrL = np.array(mylist)
myArrL

array([1, 2, 3])

In [8]:
# 2d array

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
mat.shape

(3, 3)

In [10]:
myArrL.shape

(3,)

In [11]:
mat[1,1]

5

In [12]:
mat[2,2]

9

In [17]:
arrn = np.arange(0,11,2).reshape(2,3)
arrn

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [18]:
arrn.shape

(2, 3)

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
# random function
arrR = np.random.randint(0,100,10).reshape(5,2)
arrR

array([[35, 48],
       [54, 35],
       [ 0, 69],
       [36,  1],
       [37, 58]])

In [32]:
np.random.seed(101)

In [34]:
arrR = np.random.randint(0,100,10).reshape(5,2)
arrR

array([[ 4, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]])

In [35]:
# max, min, max index, min index, mean
arrR.max()

93

In [36]:
arrR.min()

4

In [37]:
arrR.argmax()

8

In [38]:
arrR.argmin()

0

In [39]:
arrR.mean()

47.3

In [40]:
nArr = np.arange(0,11,2)
nArr

array([ 0,  2,  4,  6,  8, 10])

In [41]:
nArr[1:-2]=100
nArr

array([  0, 100, 100, 100,   8,  10])

In [42]:
slice_of_Array = nArr[0:4]

In [43]:
slice_of_Array[:] = 200

In [44]:
slice_of_Array

array([200, 200, 200, 200])

In [45]:
nArr

array([200, 200, 200, 200,   8,  10])

In [46]:
arr_copy = nArr.copy()
arr_copy

array([200, 200, 200, 200,   8,  10])

In [47]:
nArr

array([200, 200, 200, 200,   8,  10])

In [48]:
arr_copy[:]  = 1000

In [49]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000])

In [50]:
nArr

array([200, 200, 200, 200,   8,  10])

In [51]:
arr_2d = np.arange(0,100,1).reshape(10,10)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
arr_2d[2:,:5]

array([[20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]])

In [54]:
arr_2d>30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [55]:
#numpy operations 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [58]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
1/0

ZeroDivisionError: division by zero

In [60]:
arr/arr

<ipython-input-60-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
1/arr

<ipython-input-61-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [62]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [63]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [64]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [65]:
np.log(arr)

<ipython-input-65-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])